### ISSUE TITLE
More Info About Using w. Obsidian

### ISSUE THREAD

**Issue by bnew** [jerzydziewierz/PMBOK-doc-templates#3]
Hi George - I came across this repo recently and was wondering if you could add more to your readme or elaborate on how to use these templates with Obsidian. I tried following your instructions along with the PMBOK guide but got a bit lost...Thanks!!!!

**Comment by jerzydziewierz** [comment]
Action: Verify that following the guide from the `README.md` is possible. 
Constraints: Do not assume that anything that is not in `README` is available to the user.

**Comment by jerzydziewierz** [comment]
Hey @bnew , is this still a problem?
I had a look at it, 
these documents are a plan template, that is, you can copy & paste the headlines and then fill the content

Going with the spirit of PMBOK Guide, you can and should choose which headlines to use, and also rename them as needed

The only thing that PMBOK stipulates is that, when starting a new project, you should at least review & consider all these categories of problems. 

Does this help?
